Repository BrainStorming-Algorithm/BrainStorming, pull requests merged in 2021-07, with the labels that each got.

#22 한번 봐주시라요
  .vscode/settings.json
  Jeongsik/20210627/binaryGap.py
  Jeongsik/20210627/openChat.py
  Jeongsik/20210627/twoNum.py
  Jeongsik/20210627/twoSum.py
Labels: help wanted

#28 기능개발, Arrays 완료
  ChoiInnSun/arrays_codility.py
  ChoiInnSun/binary.py
  ChoiInnSun/funtionDev.py
Labels: 2 solved

#29 프로그래머스 - 서울에서 김서방 찾기
  ChoiInnSun/findkim.py
Labels: 1 solved
